# Generated by Django 4.2.3 on 2023-07-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_doc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='annotated_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='annotation',
            name='document',
            field=models.CharField(max_length=1000),
        ),
    ]
