# Generated by Django 4.2.3 on 2023-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_doc', '0002_rename_annotated_text_annotation_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
